/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppUsersLayoutRouteImport } from './pages/_app/users/layout'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AppUsersIndexRouteImport } from './pages/_app/users/index'
import { Route as AppScheduleIndexRouteImport } from './pages/_app/schedule/index'
import { Route as AppDashboardIndexRouteImport } from './pages/_app/dashboard/index'
import { Route as AppClientsIndexRouteImport } from './pages/_app/clients/index'
import { Route as AppBookingsIndexRouteImport } from './pages/_app/bookings/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersLayoutRoute = AppUsersLayoutRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersLayoutRoute,
} as any)
const AppScheduleIndexRoute = AppScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthLayoutRouteWithChildren
  '/users': typeof AppUsersLayoutRouteWithChildren
  '/bookings/': typeof AppBookingsIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/schedule/': typeof AppScheduleIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthLayoutRouteWithChildren
  '/bookings': typeof AppBookingsIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/schedule': typeof AppScheduleIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/users': typeof AppUsersLayoutRouteWithChildren
  '/_app/bookings/': typeof AppBookingsIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/schedule/': typeof AppScheduleIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/bookings/'
    | '/clients/'
    | '/dashboard/'
    | '/schedule/'
    | '/users/'
    | '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/clients'
    | '/dashboard'
    | '/schedule'
    | '/users'
    | '/sign-in'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/users'
    | '/_app/bookings/'
    | '/_app/clients/'
    | '/_app/dashboard/'
    | '/_app/schedule/'
    | '/_app/users/'
    | '/_auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersLayoutRoute
    }
    '/_app/schedule/': {
      id: '/_app/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AppScheduleIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/bookings/': {
      id: '/_app/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppUsersLayoutRouteChildren {
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersLayoutRouteChildren: AppUsersLayoutRouteChildren = {
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersLayoutRouteWithChildren = AppUsersLayoutRoute._addFileChildren(
  AppUsersLayoutRouteChildren,
)

interface AppLayoutRouteChildren {
  AppUsersLayoutRoute: typeof AppUsersLayoutRouteWithChildren
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppScheduleIndexRoute: typeof AppScheduleIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppUsersLayoutRoute: AppUsersLayoutRouteWithChildren,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppScheduleIndexRoute: AppScheduleIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
