/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'

const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in'
  id: '__root__' | '/_auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
